### ISSUE TITLE
openjdk 1.8 net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)         at net.sf.marineapi.nmea.event.AbstractSentenceListener.<init>(AbstractSentenceListener.java:77)

### ISSUE THREAD

**Issue by songhaonangit** [ktuukkan/marine-api#103] opened 2019-04-04 10:16 UTC
2019-04-04 18:11:30.388 8411-8411/? E/AndroidRuntime:     at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
2019-04-04 18:11:30.388 8411-8411/? E/AndroidRuntime:     at net.sf.marineapi.util.GenericTypeResolver.resolve(GenericTypeResolver.java:57)
        at net.sf.marineapi.nmea.event.AbstractSentenceListener.<init>(AbstractSentenceListener.java:77)

**Comment by ktuukkan** [comment] 2019-04-08 13:46
Any context or additional info for this?

**Comment by ktuukkan** [comment] 2019-10-19 15:15
Unable to reproduce, thus closing for now.

**Closed by ktuukkan** 2019-10-19 15:15 UTC
